#!/bin/bash
if [[ !(-n $(pidof i3lock)) ]]; then
  import -silent -window root png:- | convert -blur 0x20 png:- png:- | composite -gravity Southeast -geometry -10x120 ~/Pictures/rick.png png:- png:- > ${HOME}/tmp/lock-tmp.png
  i3lock -i ${HOME}/tmp/lock-tmp.png
  rm ${HOME}/tmp/lock-tmp.png
fi
